-- 삭제
DROP TABLE PROCEEDING;
DROP TABLE PROJECT;
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

-- 부서 테이블
CREATE TABLE DEPARTMENT (
    DEPT_NO       VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME     VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL,
    CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NO)
);

-- 사원 테이블
CREATE TABLE EMPLOYEE (
    EMP_NO    NUMBER NOT         NULL,
    DEPT_NO   VARCHAR2(15 BYTE)  NULL,
    POSITION  CHAR(10 BYTE)      NULL,
    NAME      VARCHAR2(15 BYTE)  NULL,
    HIRE_DATE DATE               NULL,
    SALARY    NUMBER             NULL,
    CONSTRAINT PK_EMP PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO) ON DELETE SET NULL -- DEPT_NO는 NULL일 수도 있다. (부서는 없어질 수 있다, 사원정보에 NULL값을 넣을 수 있게 하자. 새로운 부서번호 생기면 넣어줄 수 있게 해주자.)
);                                                                                                -- 부서가 없어지면 사원의 부서정보만 NULL처리된다.

-- 프로젝트 테이블
CREATE TABLE PROJECT (
    PJT_NO     NUMBER            NOT NULL,
    PJT_NAME   VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE              NULL,
    END_DATE   DATE              NULL,
    CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO)
);

-- 프로젝트 진행 테이블
CREATE TABLE PROCEEDING (
    PCD_NO    NUMBER NOT NULL,
    EMP_NO    NUMBER NULL,
    PJT_NO    NUMBER NULL,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCD PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PCD_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) ON DELETE SET NULL,
    CONSTRAINT FK_PCD_PJT FOREIGN KEY(PJT_NO) REFERENCES PROJECT(PJT_NO) ON DELETE SET NULL
);