-- 사원 번호를 전달하면 해당 사원의 이름을 반환하는 함수 만들기

CREATE OR REPLACE FUNCTION GET_NAME(EMPNO EMPLOYEE_TBL.EMP_NO%TYPE)
RETURN VARCHAR2
IS 
    EMPNAME EMPLOYEE_TBL.NAME%TYPE;
BEGIN
    SELECT NAME
      INTO EMPNAME   -- NAME은 EMPNAME에 저장한다.
      FROM EMPLOYEE_TBL
     WHERE EMP_NO = EMPNO;
    RETURN EMPNAME;
END;


-- 1001번 호출하면 
-- 사원명
-- 구창민

SELECT GET_NAME(1001) AS 사원명
  FROM EMPLOYEE_TBL
 WHERE EMP_NO = 1001;

-- 1번만 보여달라
SELECT DISTINCT GET_NAME(1001) AS 사원명
  FROM EMPLOYEE_TBL;

-- 전체를 보고싶으면
SELECT GET_NAME(EMP_NO) AS 사원명
  FROM EMPLOYEE_TBL;
